# Generated by Django 4.2.10 on 2024-02-24 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentslist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="giftlinks",
            name="gift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="presents.gift",
            ),
        ),
        migrations.AddField(
            model_name="giftimages",
            name="gift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="presents.gift",
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="presents.presentslist"
            ),
        ),
        migrations.AddField(
            model_name="bookedgifts",
            name="gift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="presents.gift"
            ),
        ),
        migrations.AddField(
            model_name="bookedgifts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
