# Generated by Django 4.2.11 on 2024-03-20 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts",
                to="presents.presentslist",
            ),
        ),
        migrations.AlterField(
            model_name="presentslist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
